# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  command = "next build && next export"
  publish = "out"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"